# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 26da80de470dacf7f1b7ff899b450655145e30b971865d3f56b8b7e91f1866bfff8866823f08da0bd8552e7ca3376b7b3198c4ef70535dd74a50f3984a6836c3

test:
  secret_key_base: 628bac8bfd25ed9d7584cdc0b0e42ea507d64bb1aeba7107b689a5c00d9241a968112d9fe33b1d28d8d2b5dadfcc395c1b4d85cb22af7379746d754999e237ec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
